-- MySQL Script generated by MySQL Workbench
-- Fri Dec  6 08:43:53 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_framework
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_framework` ;

-- -----------------------------------------------------
-- Schema db_framework
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_framework` DEFAULT CHARACTER SET utf8 ;
USE `db_framework` ;

-- -----------------------------------------------------
-- Table `db_framework`.`conta_con`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_framework`.`conta_con` ;

CREATE TABLE IF NOT EXISTS `db_framework`.`conta_con` (
  `id_conta` INT(11) NOT NULL AUTO_INCREMENT,
  `ds_usuario_con` VARCHAR(20) NOT NULL,
  `ds_email_con` VARCHAR(120) NOT NULL,
  `ds_senha_con` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_conta`),
  UNIQUE INDEX `ds_usuario_con` (`ds_usuario_con` ASC),
  UNIQUE INDEX `ds_email_con` (`ds_email_con` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_framework`.`grupo_gru`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_framework`.`grupo_gru` ;

CREATE TABLE IF NOT EXISTS `db_framework`.`grupo_gru` (
  `id_grupo` INT(11) NOT NULL AUTO_INCREMENT,
  `ds_nome_gru` VARCHAR(20) NOT NULL,
  `ds_descricao_gru` VARCHAR(80) NULL DEFAULT NULL,
  PRIMARY KEY (`id_grupo`),
  UNIQUE INDEX `ds_nome_gru` (`ds_nome_gru` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_framework`.`conta_grupo_cgr`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_framework`.`conta_grupo_cgr` ;

CREATE TABLE IF NOT EXISTS `db_framework`.`conta_grupo_cgr` (
  `id_conta_cgr` INT(11) NOT NULL,
  `id_grupo_cgr` INT(11) NOT NULL,
  PRIMARY KEY (`id_conta_cgr`, `id_grupo_cgr`),
  INDEX `id_grupo_cgr` (`id_grupo_cgr` ASC),
  CONSTRAINT `conta_grupo_cgr_ibfk_1`
    FOREIGN KEY (`id_conta_cgr`)
    REFERENCES `db_framework`.`conta_con` (`id_conta`),
  CONSTRAINT `conta_grupo_cgr_ibfk_2`
    FOREIGN KEY (`id_grupo_cgr`)
    REFERENCES `db_framework`.`grupo_gru` (`id_grupo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_framework`.`setor_set`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_framework`.`setor_set` ;

CREATE TABLE IF NOT EXISTS `db_framework`.`setor_set` (
  `id_setor` INT(11) NOT NULL AUTO_INCREMENT,
  `cd_empresa_set` VARCHAR(4) NULL DEFAULT NULL,
  `cd_diretoria_set` VARCHAR(4) NULL DEFAULT NULL,
  `cd_setor_set` VARCHAR(4) NULL DEFAULT NULL,
  `ds_sigla_set` VARCHAR(10) NULL DEFAULT NULL,
  `ds_nome_set` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_setor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_framework`.`usuario_usu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_framework`.`usuario_usu` ;

CREATE TABLE IF NOT EXISTS `db_framework`.`usuario_usu` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `ds_nome_completo_usu` VARCHAR(60) NULL DEFAULT NULL,
  `ds_nome_guerra_usu` VARCHAR(45) NULL DEFAULT NULL,
  `ds_data_nasc_usu` DATETIME NULL DEFAULT NULL,
  `ds_matricula_usu` VARCHAR(50) NULL DEFAULT NULL,
  `ds_cpf_usu` VARCHAR(50) NULL DEFAULT NULL,
  `ds_foto_usu` VARCHAR(20) NULL DEFAULT NULL,
  `setor_id` INT(11) NULL DEFAULT NULL,
  `conta_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `setor_id` (`setor_id` ASC),
  UNIQUE INDEX `conta_id` (`conta_id` ASC),
  CONSTRAINT `usuario_usu_ibfk_1`
    FOREIGN KEY (`setor_id`)
    REFERENCES `db_framework`.`setor_set` (`id_setor`),
  CONSTRAINT `usuario_usu_ibfk_2`
    FOREIGN KEY (`conta_id`)
    REFERENCES `db_framework`.`conta_con` (`id_conta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
